### ISSUE TITLE
Different behavior than GALasm on comments in file

### ISSUE THREAD

**Issue by sorphin** [simon-frankau/galette#13]
Example: PLD file is as such:
```
GAL22V10 ; The device type
gal-test ; The signature

; Pin definitions:
;   1st line: Pins 1 - 12
;   2nd line: Pins 13 - 24

A   B   NC  NC  NC  NC  NC  NC  NC  NC  NC  GND
NC  NC  NC  NC  NC  Z   Y   X   W   V   U   VCC

; Logic equations

U = /A
V = A + B
W = A * B
/X = A * B
/Y = A + B
Z = /A * B + A * /B

DESCRIPTION:
This file creates the following gates with
only the two inputs A and B:
    U = NOT (only uses A)
    V = OR
    W = AND
    X = NAND
    Y = NOR
    Z = XOR
```

GALasm result:
```
$ galasm -v gal-test.pld 
GALasm 2.1, Portable GAL Assembler
Copyright (c) 1998-2003 Alessandro Zummo. All Rights Reserved
Original sources Copyright (c) 1991-96 Christian Habermann

Assembler Phase 1 for "gal-test.pld"
Assembler Phase 2 for "gal-test.pld"
GAL22V10; Security fuse off
Assembling successfully completed.
```

Galette result:
```
$ galette gal-test.pld 
gal-test.pld: Error in line 1: type of GAL expected
```

If I remove the comment on each line, it works.  It's not just this example file, there are other files from projects that it has the same issue with (i.e. micro_8088).  So not sure if this behavior is accidental or purposeful?

**Comment by simon-frankau** [comment]
Hi. Sorry I didn't get back to you earlier. Somehow my spam filter has decided it hates github!

Let me take a quick look and get back to you - it's been a while since I've worked on this code, now.

**Comment by simon-frankau** [comment]
Looking at the source, it seems deliberate, but I can't really think why, beyond wanting to ensure the file is well-structured in some way. It seems like an unreasonable restriction, so I'll try removing it and seeing if anything happens!

The best excuse I can think of is that it allows semi-colons in the signature, but that seems a pretty obscure corner case.

**Comment by simon-frankau** [comment]
Huh. I'm slightly surprised that mentioning the issue in my commit message auto-closes it (I'm not a very regular github user), but, yeah, I've had a go at fixing this. Please feel free to take a look and re-open if I've missed anything. Thanks.
