### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by fabianschuiki** [simon-frankau/galette#4]
This is a very nice piece of code. It would be great to have it listed on crates.io, so people can just type `cargo install galette` on their system. How about running a `cargo publish` on your end :smiley: ? Also :+1: for the crate name!

**Comment by simon-frankau** [comment]
Thanks for suggesting this - I hadn't considered it!

It's now up at https://crates.io/crates/galette. Please tell me if you see anything odd, as this is the first time I've put anything on crates.io. Cheers!

**Comment by fabianschuiki** [comment]
Awesome, thanks a lot :+1: :smile:
