### ISSUE TITLE
Long broken lines of terms don't seem to be processed like galasm

### ISSUE THREAD

**Issue by storeilly** [simon-frankau/galette#6]
I installed galasm before I found galette and thank you to everyone involved for a job well done.

I've noticed that if I break a long line of terms, galette complains but galasm works through no problem. Example code below, it complains of "unexpected token in lilne 12"

==================
GAL22V10
soreilly

;       1       2       3       4       5       6       7       8       9       10      11      12 
        In01    In02    In03    In04    In05    In06    In07    In08    In09    In10    In11    GND     ;       (Inputs)
        In13    IO14    IO15    IO16    IO17    IO18    IO19    IO20    IO21    IO22    IO23    VCC     ;       (13=In)(10InOutputs)

IO23 = In01  *  In02
IO22 = In03  *  In04
IO21 = In05  +  In06
  *  In07  *  In08  *  In09  *  In10  *  In11  *  In13
   * IO14  * IO15 * IO16 * IO17 * IO18 * IO19 * IO20 * IO21

**Comment by simon-frankau** [comment]
(I've just reminded myself of the parser code, and it looks like it's made some fairly strong "we can process this line by line" assumptions. Shouldn't be a problem, just needs a little more thinking to do this cleanly.)

**Comment by simon-frankau** [comment]
This is now fixed as of https://github.com/simon-frankau/galette/commit/4347233d23d5716b4f06e047bc260dfa5e1e0f23. I should probably have created a PR for myself and approved it to make the fix commits clear, but I didn't, so here we are. :)

Please feel free to reopen the issue if you have any problems.
